project:
  type: book
  output-dir: docs



book:
  title: "Turbocharge ML with JAX and TPUs"
  author: "RA Stringer"
  date: "6/2/2023"
  cover-image: jax_xla.png
  repo-url: https://github.com/rastringer/turbocharge_ml_jax_tpu
  chapters:
    - index.qmd
    - TPUs.ipynb
    - JAX_foundations.ipynb
    - jax_linear_regression.ipynb
    - exercise1_jax_mnist.ipynb
    - flax_foundations.ipynb
    - exercise2_linear_reg_flax.ipynb
    - Resnet.ipynb
    - diffusion.ipynb
    - stable_diffusion.ipynb
    - vit_jax.ipynb 
    - exercise1_jax_mnist_solution.ipynb
    - exercise2_solution.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



